name: flip_notes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flex_color_picker: ^3.6.0
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  intl: ^0.19.0
  riverpod_annotation: ^2.6.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
