name: flip_notes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  collection: ^1.18.0
  dev: ^1.0.0
  flex_color_picker: ^3.6.0
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  intl: ^0.19.0
  path: ^1.9.0
  riverpod_annotation: ^2.6.1
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+4
  sqlite3_flutter_libs: ^0.5.27
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint: ^0.7.0
  flutter_lints: ^4.0.0
  riverpod_lint: ^2.6.3
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3

flutter:
  uses-material-design: true
